(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

Module policy.
  Module context.
    (* StructRecord
      {
        name := "ExpressionEvalContext";
        ty_params := [];
        fields :=
          [
            ("df",
              Ty.apply (Ty.path "&") [ Ty.path "picachv_core::dataframe::PolicyGuardedDataFrame" ]);
            ("in_agg", Ty.path "bool");
            ("gb_proxy",
              Ty.apply
                (Ty.path "core::option::Option")
                [ Ty.apply (Ty.path "&") [ Ty.path "picachv_message::group_by_idx::Groups" ] ]);
            ("udfs",
              Ty.apply
                (Ty.path "&")
                [
                  Ty.apply
                    (Ty.path "std::collections::hash::map::HashMap")
                    [
                      Ty.path "alloc::string::String";
                      Ty.path "picachv_core::udf::Udf";
                      Ty.path "std::hash::random::RandomState"
                    ]
                ]);
            ("arena", Ty.apply (Ty.path "&") [ Ty.path "picachv_core::Arenas" ])
          ];
      } *)
    
    Module Impl_picachv_core_policy_context_ExpressionEvalContext.
      Definition Self : Ty.t := Ty.path "picachv_core::policy::context::ExpressionEvalContext".
      
      (*
          pub fn new(
              df: &'ctx PolicyGuardedDataFrame,
              in_agg: bool,
              udfs: &'ctx HashMap<String, Udf>,
              arena: &'ctx Arenas,
          ) -> Self {
              ExpressionEvalContext {
                  df,
                  in_agg,
                  gb_proxy: None,
                  udfs,
                  arena,
              }
          }
      *)
      Definition new (τ : list Ty.t) (α : list Value.t) : M :=
        match τ, α with
        | [], [ df; in_agg; udfs; arena ] =>
          ltac:(M.monadic
            (let df := M.alloc (| df |) in
            let in_agg := M.alloc (| in_agg |) in
            let udfs := M.alloc (| udfs |) in
            let arena := M.alloc (| arena |) in
            Value.StructRecord
              "picachv_core::policy::context::ExpressionEvalContext"
              [
                ("df", M.read (| df |));
                ("in_agg", M.read (| in_agg |));
                ("gb_proxy", Value.StructTuple "core::option::Option::None" []);
                ("udfs", M.read (| udfs |));
                ("arena", M.read (| arena |))
              ]))
        | _, _ => M.impossible
        end.
      
      Axiom AssociatedFunction_new : M.IsAssociatedFunction Self "new" new.
    End Impl_picachv_core_policy_context_ExpressionEvalContext.
  End context.
End policy.
