[package]
name = "picachv-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
crate-type = ["cdylib", "rlib"]

[dependencies]
picachv-error = { workspace = true }
picachv-message = { workspace = true }
polars-core = { workspace = true }
polars-utils = { workspace = true }

tabled = { version = "0.15.0" }
log = { workspace = true }
num_enum = { workspace = true }
ordered-float = { workspace = true }
uuid = { workspace = true }
