[package]
name = "picachv-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
picachv-error = { workspace = true }
polars-core = { workspace = true }
polars-utils = { workspace = true }
picachv-message = { workspace = true }

ordered-float = { workspace = true }
uuid = { workspace = true }
num_enum = { workspace = true }
