[package]
name = "picachv-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "4.2.0"
picachv-error = { workspace = true }
polars-core = { workspace = true }
polars-utils = { workspace = true }
